softeerbootcamp4th/Team1-Strawberry-BE

build.gradle
src/main/java/com/hyundai/softeer/backend/global/config/SwaggerConfig.java

- Swagger Configuration 설정
- Title, Description, Version
- Tag 설정
- JWT access-token 설정 추가

#4 feat: Swagger Configuration

---

build.gradle
src/main/java/com/hyundai/softeer/backend/global/config/SwaggerConfig.java

- #4 
- API 문서화 작업을 위한 Swagger 도입
- Swagger 설정
- #4

Swagger 설정을 추가합니다.

---

build.gradle
src/main/java/com/hyundai/softeer/backend/domain/user/controller/AuthController.java
src/main/java/com/hyundai/softeer/backend/domain/user/dto/HyundaiUserInfo.java
src/main/java/com/hyundai/softeer/backend/domain/user/dto/LoginResponseDto.java
src/main/java/com/hyundai/softeer/backend/domain/user/dto/NaverUserInfo.java
src/main/java/com/hyundai/softeer/backend/domain/user/dto/UserInfoDto.java
src/main/java/com/hyundai/softeer/backend/domain/user/entity/User.java
src/main/java/com/hyundai/softeer/backend/domain/user/repository/UserRepository.java
src/main/java/com/hyundai/softeer/backend/domain/user/service/HyundaiOauthService.java
src/main/java/com/hyundai/softeer/backend/domain/user/service/NaverOauthService.java
src/main/java/com/hyundai/softeer/backend/global/jwt/OAuthProvider.java
src/main/java/com/hyundai/softeer/backend/global/jwt/dto/TokenDto.java
src/main/java/com/hyundai/softeer/backend/global/jwt/provider/HyundaiTokens.java
src/main/java/com/hyundai/softeer/backend/global/jwt/provider/NaverTokens.java
src/main/java/com/hyundai/softeer/backend/global/jwt/provider/TokenProvider.java

- #22 
- 사용자 식별을 위한 SNS 로그인 구현
- Naver 로그인 구현
- 현대자동차 로그인 구현
- #22

SNS 로그인 기능 추가합니다.

---

src/main/java/com/hyundai/softeer/backend/global/filter/JwtAuthorizationFilter.java

- #24 
- 인가 처리를 위한 JWT 필터 등록
- JWT 필터 생성 및 에러 처리
- #24

인가를 위한 JWT Filter 구현합니다.

---

src/main/java/com/hyundai/softeer/backend/global/config/WebConfig.java
src/main/java/com/hyundai/softeer/backend/global/filter/JwtAuthorizationFilter.java

- #24 
- 인가 처리를 위한 JWT 필터 등록
- JWT 필터 생성 및 에러 처리
- #24

인가를 위한 JWT 필터 구현합니다.

---

src/main/java/com/hyundai/softeer/backend/domain/user/dto/AuthenticateUser.java
src/main/java/com/hyundai/softeer/backend/global/config/WebConfig.java
src/main/java/com/hyundai/softeer/backend/global/filter/JwtAuthorizationFilter.java

- #24 
- 인가 처리를 위한 JWT 필터 등록
- JWT 필터 생성 및 에러 처리
- #24

인가를 위한 JWT 필터 생성합니다.

---

src/main/java/com/hyundai/softeer/backend/BackendApplication.java
src/main/java/com/hyundai/softeer/backend/domain/event/entity/Event.java
src/main/java/com/hyundai/softeer/backend/domain/subevent/entity/SubEvent.java
src/main/java/com/hyundai/softeer/backend/domain/user/controller/AuthController.java
src/main/java/com/hyundai/softeer/backend/domain/user/entity/User.java
src/main/java/com/hyundai/softeer/backend/domain/user/service/HyundaiOauthService.java
src/main/java/com/hyundai/softeer/backend/domain/user/service/NaverOauthService.java
src/main/java/com/hyundai/softeer/backend/global/dto/BaseEntity.java
src/main/java/com/hyundai/softeer/backend/global/dto/BaseResponse.java
src/main/java/com/hyundai/softeer/backend/global/status/BaseResponseStatus.java

- #35 
- CreatedAt, ModifiedAt 을 위한 BaseEntity
- 응답 메세지 통일을 위한 BaseResponse
- BaseEntity
- BaseResponse
- BaseResponseStatus (Custom status code, message)
```
{
"status": 2000,
"message": "success",
"data": {
"user": {
"id": 1,
"email": "user@user.com",
"name": "이름",
"birthdate": "2000-01-01",
"phoneNumber": "010-1234-1234"
},
"token": {
"accessToken": " ... ",
"refreshToken": " ... "
}
}
}
```
- #35

BaseEntity, BaseResponse 생성

---

src/main/java/com/hyundai/softeer/backend/domain/user/controller/AuthController.java
src/main/java/com/hyundai/softeer/backend/domain/user/dto/UserInfoDto.java
src/main/java/com/hyundai/softeer/backend/global/jwt/dto/TokenDto.java

- #41 
- 로그인 부분 Swagger 문서화 작업 미흡
- User Tag 사용
- API 별 Description 작성
- DTO 예시 작성
- #41

로그인 API Swagger 정리 추가합니다.

---

src/main/java/com/hyundai/softeer/backend/global/config/WebConfig.java
src/main/java/com/hyundai/softeer/backend/global/exception/UsernameNotFoundException.java
src/main/java/com/hyundai/softeer/backend/global/jwt/CurrentUser.java
src/main/java/com/hyundai/softeer/backend/global/jwt/CurrentUserMethodArgumentResolver.java
src/main/java/com/hyundai/softeer/backend/global/jwt/UserDetailService.java
src/main/java/com/hyundai/softeer/backend/global/jwt/dto/TokenDto.java
src/main/java/com/hyundai/softeer/backend/global/jwt/provider/TokenProvider.java

- #45 
- JWT 사용 시 유저 식별을 위한 어노테이션 생성
- CurrentUser 어노테이션 생성
- 어노테이션 처리를 위한 ArgumentResolver 생성
- 실제 유저 정보 조회를 위한 UserDetailService 생성
- #45

JWT 유저 파싱을 위한 어노테이션 추가합니다.

---

src/main/java/com/hyundai/softeer/backend/domain/firstcomeevent/quiz/service/QuizService.java
src/main/java/com/hyundai/softeer/backend/domain/subevent/dto/WinnerInfo.java
src/main/java/com/hyundai/softeer/backend/domain/user/controller/AuthController.java
src/main/java/com/hyundai/softeer/backend/global/config/CorsConfig.java
src/main/java/com/hyundai/softeer/backend/global/utils/ParseUtil.java
src/test/java/com/hyundai/softeer/backend/global/utils/ParseUtilTest.java

- #48 
- 클라이언트의 cors 문제를 해결하기 위해
- CorsConfig를 통해 cors 정책을 설정해주었어요
- 클라이언트는 naver api를 js로 호출하면 안되기 때문에 (window.location.href) 사용을 해야합니다.
스크린샷을 첨부해주세요.
- client에서 JS를 쓰지 못하기 때문에 GET 메소드가 강제된다. (POST를 사용할 수 없음)

cors 구성 파일 추가했어요.

---

src/main/java/com/hyundai/softeer/backend/domain/firstcomeevent/quiz/advice/QuizControllerAdvice.java
src/main/java/com/hyundai/softeer/backend/domain/firstcomeevent/quiz/controller/QuizController.java
src/main/java/com/hyundai/softeer/backend/global/config/SwaggerConfig.java
src/main/java/com/hyundai/softeer/backend/global/dto/BaseResponse.java
src/main/java/com/hyundai/softeer/backend/global/filter/JwtAuthorizationFilter.java

- #66 
- 문서화가 부실함
- BaseResponse 추가로 인한 코드 변경 필요
- 스웨거 제네릭 타입 적용 필요성
- 기존 api의 반환 값을 BaseResponse로 wrapping 함
- 문서 고도화 완료

quiz api 문서 고도화 및 BaseResponse 적용

---

src/main/java/com/hyundai/softeer/backend/domain/event/dto/ApiKeyRequest.java
src/main/java/com/hyundai/softeer/backend/domain/event/dto/EventRequest.java
src/main/java/com/hyundai/softeer/backend/domain/event/service/EventService.java
src/main/java/com/hyundai/softeer/backend/domain/eventuser/repository/EventUserRepository.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/controller/DrawingLotteryController.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryService.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/dto/RankDto.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/entity/LotteryEvent.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/exception/AlreadyDrawedException.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/service/LotteryService.java
src/main/java/com/hyundai/softeer/backend/domain/prize/entity/Prize.java
src/main/java/com/hyundai/softeer/backend/domain/subevent/dto/SubEventRequest.java
src/main/java/com/hyundai/softeer/backend/domain/subevent/dto/WinnerCandidate.java
src/main/java/com/hyundai/softeer/backend/domain/subevent/dto/WinnerInfo.java
src/main/java/com/hyundai/softeer/backend/domain/subevent/repository/SubEventRepository.java
src/main/java/com/hyundai/softeer/backend/domain/user/entity/User.java
src/main/java/com/hyundai/softeer/backend/domain/winner/entity/Winner.java
src/main/java/com/hyundai/softeer/backend/domain/winner/repository/WinnerRepository.java
src/main/java/com/hyundai/softeer/backend/global/config/SwaggerConfig.java
src/main/java/com/hyundai/softeer/backend/global/exception/error/JsonParseException.java
src/main/java/com/hyundai/softeer/backend/global/filter/JwtAuthorizationFilter.java
src/main/java/com/hyundai/softeer/backend/global/utils/ParseUtil.java
src/test/java/com/hyundai/softeer/backend/domain/expectation/service/ExpectationServiceTest.java
src/test/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryServiceTest.java
src/test/java/com/hyundai/softeer/backend/domain/lottery/service/LotteryServiceTest.java
src/test/java/com/hyundai/softeer/backend/global/utils/ParseUtilTest.java

- #37 
- 드로잉 이벤트 추첨 구현
- 데이터베이스에서 N * M 명 랜덤 추첨
- N * M 명 점수 계산 후 N 명 추첨
- #37

추첨 이벤트 추첨 구현

---

src/main/java/com/hyundai/softeer/backend/domain/eventuser/controller/EventUserController.java
src/main/java/com/hyundai/softeer/backend/domain/eventuser/exception/EventUserNotFoundException.java
src/main/java/com/hyundai/softeer/backend/domain/eventuser/repository/EventUserRepository.java
src/main/java/com/hyundai/softeer/backend/domain/eventuser/service/EventUserService.java
src/test/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryServiceTest.java
src/test/java/com/hyundai/softeer/backend/domain/lottery/service/LotteryServiceTest.java

- #94 
- EventUser Notfound 시 500 에러 반환
- Swagger 문서화 Drawing 특정 이벤트로 작성되어있음
- Swagger 문서화 변경
- Notfound 시 404 및 메세지 반환 

EventUser Info API 변경합니다.

---

build.gradle
src/main/java/com/hyundai/softeer/backend/domain/event/entity/Event.java
src/main/java/com/hyundai/softeer/backend/domain/eventuser/repository/EventUserRepository.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryService.java
src/test/java/com/hyundai/softeer/backend/domain/eventuser/repository/EventUserRepositoryTest.java
src/test/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryServiceTest.java
src/test/resources/sql/integration-h2.sql

- #96 
- 레포지터리단 단위테스트 작성
- 내장 H2 사용
-  초기 SQL 문 작성
- EventUserRepositoryTest

EventUserRepository 단위 테스트

---

src/main/java/com/hyundai/softeer/backend/domain/event/entity/Event.java
src/main/java/com/hyundai/softeer/backend/domain/firstcomeevent/quiz/service/QuizService.java
src/test/java/com/hyundai/softeer/backend/domain/expectation/repository/ExpectationRepositoryTest.java
src/test/java/com/hyundai/softeer/backend/domain/subevent/repository/SubEventRepositoryTest.java
src/test/resources/sql/integration-h2.sql

- #102 
- 병합 실수
- sql 파일 수정 (h2 JSON 타입)
- JSON 문자열 추가 시 (JSON 키워드 추가)
- 코드 중복 해결
스크린샷을 첨부해주세요.

sql 파일 수정 및 병합으로 인한 코드 중복 해결

---

src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/controller/DrawingLotteryController.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryService.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/entity/LotteryEvent.java
src/main/java/com/hyundai/softeer/backend/domain/subevent/controller/SubEventController.java
src/main/java/com/hyundai/softeer/backend/domain/subevent/entity/SubEvent.java
src/main/java/com/hyundai/softeer/backend/domain/subevent/service/SubEventService.java
src/test/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryServiceTest.java
src/test/java/com/hyundai/softeer/backend/domain/subevent/service/SubEventServiceTest.java
src/test/resources/sql/integration-h2.sql

- #108 
- 드로잉 추첨 이벤트 테이블 변경
- 드로잉 추첨 이벤트 테이블 변경
- 추첨 메서드 도메인 변경
스크린샷을 첨부해주세요.

드로잉 추첨 이벤트 테이블 및 추첨 메서드 도메인 변경합니다.

---

src/main/java/com/hyundai/softeer/backend/domain/eventuser/entity/EventUser.java
src/main/java/com/hyundai/softeer/backend/domain/eventuser/exception/NoChanceUserException.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/controller/DrawingLotteryController.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/dto/DrawingGameInfoDto.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/dto/DrawingInfoDtos.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/dto/DrawingInfoRequest.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryService.java
src/main/java/com/hyundai/softeer/backend/domain/subevent/enums/EventPlayType.java
src/main/java/com/hyundai/softeer/backend/domain/subevent/exception/UnknownEventPlayTypeException.java
src/main/java/com/hyundai/softeer/backend/global/exception/error/JwtException.java
src/main/java/com/hyundai/softeer/backend/global/jwt/UserDetailService.java
src/test/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryServiceTest.java

- #124 
- 게임 참여 시 기회 차감 로직 추가
- 게임 첫 참여 시 EventUser 생성
- 게임 참여 시 참여 기회 차감 및 lastVisitedAt, lastChargeAt 최신화
스크린샷을 첨부해주세요.

Feat/#126  decrease drawing chance

---

src/main/java/com/hyundai/softeer/backend/global/filter/JwtAuthorizationFilter.java

- #147 
- OPTIONS 메서드 처리 불가 
- preflight 요청 화이트리스트 추가
스크린샷을 첨부해주세요.

[BE] preflight 요청 화이트리스트 추가

---

src/main/java/com/hyundai/softeer/backend/domain/event/controller/EventController.java
src/main/java/com/hyundai/softeer/backend/domain/event/dto/EventSimpleDto.java
src/main/java/com/hyundai/softeer/backend/domain/event/repository/EventRepository.java
src/main/java/com/hyundai/softeer/backend/domain/event/service/EventService.java

- #144 
- 이벤트 조회를 위한 API 생성
- 주요 변경사항 목록을 알려주세요.
스크린샷을 첨부해주세요.

이벤트 조회 API 생성합니다. 

---

src/main/java/com/hyundai/softeer/backend/domain/event/exception/EventNotFoundException.java
src/main/java/com/hyundai/softeer/backend/domain/eventuser/controller/EventUserController.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/controller/QuizFirstComeController.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/dto/QuizFirstComeDeleteRequest.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/dto/QuizFirstComeInfoResponseDto.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/dto/QuizFirstComeRegisterRequest.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/dto/QuizInfoDto.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/entity/QuizFirstCome.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/exception/QuizAlreadyExistException.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/exception/QuizRegisterForbiddenException.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/repository/QuizFirstComeRepository.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/service/QuizFirstComeService.java
src/main/java/com/hyundai/softeer/backend/domain/subevent/dto/SubEventInfo.java
src/main/java/com/hyundai/softeer/backend/domain/subevent/repository/SubEventRepository.java
src/main/resources/sql/integration.sql
src/test/resources/sql/integration-h2.sql
src/test/resources/sql/integration.sql

- #150 
- 퀴즈 어드민 crud api 작성
- 퀴즈 조회, 생성, 삭제 api 작성
- api 키로 admin을 검사하는 로직 필요

[BE] 퀴즈 조회, 삭제, 생성 api를 작성합니다.

---

src/main/java/com/hyundai/softeer/backend/domain/eventuser/controller/EventUserController.java
src/main/java/com/hyundai/softeer/backend/domain/eventuser/dto/EventUserPageRequest.java
src/main/java/com/hyundai/softeer/backend/domain/eventuser/dto/EventUserPageResponseDto.java
src/main/java/com/hyundai/softeer/backend/domain/eventuser/dto/UserInfoDtoWithIsWinner.java
src/main/java/com/hyundai/softeer/backend/domain/eventuser/exception/EventUserPageNotFoundException.java
src/main/java/com/hyundai/softeer/backend/domain/eventuser/projection/EventUserPageProjection.java
src/main/java/com/hyundai/softeer/backend/domain/eventuser/repository/EventUserRepository.java
src/main/java/com/hyundai/softeer/backend/domain/eventuser/service/EventUserService.java
src/main/java/com/hyundai/softeer/backend/domain/subevent/exception/SubEventNotFoundException.java
src/main/java/com/hyundai/softeer/backend/global/filter/JwtAuthorizationFilter.java
src/test/java/com/hyundai/softeer/backend/domain/eventuser/repository/EventUserRepositoryTest.java

- #137 
- 이벤트 유저 정보 조회 api
- 페이지 네이션 적용
- 이벤트 유저 정보 api 작성
- 문서화

[BE] 이벤트 유저 조회 api 작성

---

src/main/java/com/hyundai/softeer/backend/domain/eventuser/entity/EventUser.java
src/main/java/com/hyundai/softeer/backend/domain/expectation/service/ExpectationService.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/dto/QuizFirstComeInfoRequest.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/dto/DrawingTotalScoreDto.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryService.java
src/main/resources/sql/integration.sql
src/test/java/com/hyundai/softeer/backend/domain/eventuser/repository/EventUserRepositoryTest.java
src/test/java/com/hyundai/softeer/backend/domain/expectation/service/ExpectationServiceTest.java

- #158 
- 각종 버그를 해결하기 위해
- EventUser의 id에 auto_increment가 안붙어있는 문제
- integration.sql의 테이블 명이 대문자인 문제
- EventUser의 sharedUrl의 디폴트 값이 존재하는 문제
- EventUser의 id에 `@GenerativeValue` 선언
- 모든 테이블 명을 소문자로 변경
- sharedUrl 디폴트 값 제거 
스크린샷을 첨부해주세요.

[BE] v1.0.6 버그 수정

---

src/main/java/com/hyundai/softeer/backend/BackendApplication.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/dto/EnqueueDto.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/dto/QueueRequest.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/dto/WaitingEnqueueBodyRequest.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/dto/WaitingQueueRequest.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/dto/WaitingQueueStatusDto.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/exception/WaitingInvalidTokenException.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/controller/QuizFirstComeController.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/dto/QuizFirstComeRequest.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/dto/QuizFirstComeSubmitRequest.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/service/QuizFirstComeService.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/scheduler/QueueScheduler.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/service/QueueService.java
src/main/java/com/hyundai/softeer/backend/global/utils/DateUtil.java

- #188 
- 오토스케일링 없이 서버의 부하를 낮추기 위해 대기열 도입
스크린샷을 첨부해주세요.

대기열을 기능 추가합니다. 

---

src/main/java/com/hyundai/softeer/backend/domain/expectation/service/ExpectationService.java
src/test/java/com/hyundai/softeer/backend/domain/expectation/service/ExpectationServiceTest.java

- #198 
- 프론트와 api 연동 중 이름 마스킹이 안되어 있는 것을 확인
- 이름 앞 뒤를 제외하고는 모든 글자가 마스킹 됩니다.
스크린샷을 첨부해주세요.

기대평 이름 마스킹 구현합니다.

---

src/main/java/com/hyundai/softeer/backend/domain/firstcome/scheduler/QueueScheduler.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryService.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/ScoreCalculator.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/rank/DrawingRankSync.java
src/main/java/com/hyundai/softeer/backend/domain/lottery/dto/RankDto.java
src/main/java/com/hyundai/softeer/backend/global/filter/JwtAuthorizationFilter.java
src/main/resources/messages.properties
src/test/java/com/hyundai/softeer/backend/domain/lottery/drawing/service/DrawingLotteryServiceTest.java

- #200 
- 랭킹 마스킹, 랜덤 메세지, 점수 하향
스크린샷을 첨부해주세요.

드로잉 이벤트 마스킹, 랜덤 메세지, 로직 변경합니다.

---

src/main/java/com/hyundai/softeer/backend/domain/expectation/service/ExpectationService.java

- #214 
- Drawing 관련 Event-user 가 없는 경우 기대평 작성이 불가능한 버그 수정
- aws s3의 Jackson 의존성 충돌 문제
```
S3: NoSuchFieldError: PASCAL_CASE_TO_CAMEL_CASE #3098
```
- 미리보기 url에 대해 요청이 가지 않는 문제
- 점수가 소수점 길게 출력되는 문제
- 기대평 작성 시 Drawing 관련 Event User 가 없으면 생성해줬습니다. 
- 미리보기 api (/lottery/drawing/preview)에 대한 요청이 가지않는 버그 수정
- 미리보기 og html의 점수를 소수점 1번째까지 넣도록 변경
- aws s3의 의존성 충돌 해결
- 해당 버그 해결 
- #214

드로잉에 대한 이벤트 유저가 없을 시 Event_user 생성합니다.

---

src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/dto/WinnerDto.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/service/winnerdraw/QuizWinnerDrawAsync.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/service/winnerdraw/QuizWinnerDrawLua.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/service/winnerdraw/QuizWinnerDrawRedis.java
src/main/java/com/hyundai/softeer/backend/domain/firstcome/quiz/service/winnerdraw/QuizWinnerDrawSync.java
src/main/java/com/hyundai/softeer/backend/global/exception/error/SQLRuntimeException.java
src/main/java/com/hyundai/softeer/backend/global/service/RedisKvService.java
src/main/java/com/hyundai/softeer/backend/global/service/RedisSetService.java

- #197 
- 요청마다 insert를 하는 것은 비효율적이라 생각하여 redis에 당첨자를 모으고 한번에 배치 작업하는게 빠를 수 있다고 생각
- 레디스 set, map 서비스로직 구현
- spring scheduler와 JDBC를 활용한 배치 작업
- lua 스크립트를 통해 당첨자 관리 
스크린샷을 첨부해주세요.

lua script와 배치를 활용한 당첨자 추첨 로직 작성합니다.
